# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello-qroma.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hello-qroma.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11hello-qroma.proto\"@\n\x14QromaHeartbeatUpdate\x12\x18\n\x10heartbeatMessage\x18\x01 \x01(\t\x12\x0e\n\x06uptime\x18\x02 \x01(\r\"!\n\x11HelloQromaRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\";\n\x0fSetColorRequest\x12\x0b\n\x03red\x18\x01 \x01(\r\x12\r\n\x05green\x18\x02 \x01(\r\x12\x0c\n\x04\x62lue\x18\x03 \x01(\r\"M\n\x12HelloQromaResponse\x12\x10\n\x08response\x18\x01 \x01(\t\x12\x11\n\tcallCount\x18\x02 \x01(\r\x12\x12\n\nnameLength\x18\x03 \x01(\r\"?\n\x0bMathRequest\x12\t\n\x01\x61\x18\x01 \x01(\r\x12\t\n\x01\x62\x18\x02 \x01(\r\x12\x1a\n\x02op\x18\x03 \x01(\x0e\x32\x0e.MathOperation\" \n\x0eMathResult_Add\x12\x0e\n\x06result\x18\x01 \x01(\r\"%\n\x13MathResult_Subtract\x12\x0e\n\x06result\x18\x01 \x01(\r\"F\n\x19MathResult_AddAndSubtract\x12\x11\n\taddResult\x18\x01 \x01(\r\x12\x16\n\x0esubtractResult\x18\x02 \x01(\r\"\xac\x01\n\x0cMathResponse\x12$\n\taddResult\x18\x01 \x01(\x0b\x32\x0f.MathResult_AddH\x00\x12.\n\x0esubtractResult\x18\x02 \x01(\x0b\x32\x14.MathResult_SubtractH\x00\x12:\n\x14\x61\x64\x64\x41ndSubtractResult\x18\x03 \x01(\x0b\x32\x1a.MathResult_AddAndSubtractH\x00\x42\n\n\x08response*d\n\rMathOperation\x12\x11\n\rMathOp_NotSet\x10\x00\x12\x0e\n\nMathOp_Add\x10\x01\x12\x13\n\x0fMathOp_Subtract\x10\x02\x12\x1b\n\x17MathOp_Add_And_Subtract\x10\x03\x62\x06proto3'
)

_MATHOPERATION = _descriptor.EnumDescriptor(
  name='MathOperation',
  full_name='MathOperation',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MathOp_NotSet', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MathOp_Add', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MathOp_Subtract', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MathOp_Add_And_Subtract', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=647,
  serialized_end=747,
)
_sym_db.RegisterEnumDescriptor(_MATHOPERATION)

MathOperation = enum_type_wrapper.EnumTypeWrapper(_MATHOPERATION)
MathOp_NotSet = 0
MathOp_Add = 1
MathOp_Subtract = 2
MathOp_Add_And_Subtract = 3



_QROMAHEARTBEATUPDATE = _descriptor.Descriptor(
  name='QromaHeartbeatUpdate',
  full_name='QromaHeartbeatUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='heartbeatMessage', full_name='QromaHeartbeatUpdate.heartbeatMessage', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='uptime', full_name='QromaHeartbeatUpdate.uptime', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=85,
)


_HELLOQROMAREQUEST = _descriptor.Descriptor(
  name='HelloQromaRequest',
  full_name='HelloQromaRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='HelloQromaRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=120,
)


_SETCOLORREQUEST = _descriptor.Descriptor(
  name='SetColorRequest',
  full_name='SetColorRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='red', full_name='SetColorRequest.red', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='green', full_name='SetColorRequest.green', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='blue', full_name='SetColorRequest.blue', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=122,
  serialized_end=181,
)


_HELLOQROMARESPONSE = _descriptor.Descriptor(
  name='HelloQromaResponse',
  full_name='HelloQromaResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='HelloQromaResponse.response', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='callCount', full_name='HelloQromaResponse.callCount', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nameLength', full_name='HelloQromaResponse.nameLength', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=183,
  serialized_end=260,
)


_MATHREQUEST = _descriptor.Descriptor(
  name='MathRequest',
  full_name='MathRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='a', full_name='MathRequest.a', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='b', full_name='MathRequest.b', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='op', full_name='MathRequest.op', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=262,
  serialized_end=325,
)


_MATHRESULT_ADD = _descriptor.Descriptor(
  name='MathResult_Add',
  full_name='MathResult_Add',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='MathResult_Add.result', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=327,
  serialized_end=359,
)


_MATHRESULT_SUBTRACT = _descriptor.Descriptor(
  name='MathResult_Subtract',
  full_name='MathResult_Subtract',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='MathResult_Subtract.result', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=361,
  serialized_end=398,
)


_MATHRESULT_ADDANDSUBTRACT = _descriptor.Descriptor(
  name='MathResult_AddAndSubtract',
  full_name='MathResult_AddAndSubtract',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='addResult', full_name='MathResult_AddAndSubtract.addResult', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='subtractResult', full_name='MathResult_AddAndSubtract.subtractResult', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=400,
  serialized_end=470,
)


_MATHRESPONSE = _descriptor.Descriptor(
  name='MathResponse',
  full_name='MathResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='addResult', full_name='MathResponse.addResult', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='subtractResult', full_name='MathResponse.subtractResult', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='addAndSubtractResult', full_name='MathResponse.addAndSubtractResult', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='response', full_name='MathResponse.response',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=473,
  serialized_end=645,
)

_MATHREQUEST.fields_by_name['op'].enum_type = _MATHOPERATION
_MATHRESPONSE.fields_by_name['addResult'].message_type = _MATHRESULT_ADD
_MATHRESPONSE.fields_by_name['subtractResult'].message_type = _MATHRESULT_SUBTRACT
_MATHRESPONSE.fields_by_name['addAndSubtractResult'].message_type = _MATHRESULT_ADDANDSUBTRACT
_MATHRESPONSE.oneofs_by_name['response'].fields.append(
  _MATHRESPONSE.fields_by_name['addResult'])
_MATHRESPONSE.fields_by_name['addResult'].containing_oneof = _MATHRESPONSE.oneofs_by_name['response']
_MATHRESPONSE.oneofs_by_name['response'].fields.append(
  _MATHRESPONSE.fields_by_name['subtractResult'])
_MATHRESPONSE.fields_by_name['subtractResult'].containing_oneof = _MATHRESPONSE.oneofs_by_name['response']
_MATHRESPONSE.oneofs_by_name['response'].fields.append(
  _MATHRESPONSE.fields_by_name['addAndSubtractResult'])
_MATHRESPONSE.fields_by_name['addAndSubtractResult'].containing_oneof = _MATHRESPONSE.oneofs_by_name['response']
DESCRIPTOR.message_types_by_name['QromaHeartbeatUpdate'] = _QROMAHEARTBEATUPDATE
DESCRIPTOR.message_types_by_name['HelloQromaRequest'] = _HELLOQROMAREQUEST
DESCRIPTOR.message_types_by_name['SetColorRequest'] = _SETCOLORREQUEST
DESCRIPTOR.message_types_by_name['HelloQromaResponse'] = _HELLOQROMARESPONSE
DESCRIPTOR.message_types_by_name['MathRequest'] = _MATHREQUEST
DESCRIPTOR.message_types_by_name['MathResult_Add'] = _MATHRESULT_ADD
DESCRIPTOR.message_types_by_name['MathResult_Subtract'] = _MATHRESULT_SUBTRACT
DESCRIPTOR.message_types_by_name['MathResult_AddAndSubtract'] = _MATHRESULT_ADDANDSUBTRACT
DESCRIPTOR.message_types_by_name['MathResponse'] = _MATHRESPONSE
DESCRIPTOR.enum_types_by_name['MathOperation'] = _MATHOPERATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

QromaHeartbeatUpdate = _reflection.GeneratedProtocolMessageType('QromaHeartbeatUpdate', (_message.Message,), {
  'DESCRIPTOR' : _QROMAHEARTBEATUPDATE,
  '__module__' : 'hello_qroma_pb2'
  # @@protoc_insertion_point(class_scope:QromaHeartbeatUpdate)
  })
_sym_db.RegisterMessage(QromaHeartbeatUpdate)

HelloQromaRequest = _reflection.GeneratedProtocolMessageType('HelloQromaRequest', (_message.Message,), {
  'DESCRIPTOR' : _HELLOQROMAREQUEST,
  '__module__' : 'hello_qroma_pb2'
  # @@protoc_insertion_point(class_scope:HelloQromaRequest)
  })
_sym_db.RegisterMessage(HelloQromaRequest)

SetColorRequest = _reflection.GeneratedProtocolMessageType('SetColorRequest', (_message.Message,), {
  'DESCRIPTOR' : _SETCOLORREQUEST,
  '__module__' : 'hello_qroma_pb2'
  # @@protoc_insertion_point(class_scope:SetColorRequest)
  })
_sym_db.RegisterMessage(SetColorRequest)

HelloQromaResponse = _reflection.GeneratedProtocolMessageType('HelloQromaResponse', (_message.Message,), {
  'DESCRIPTOR' : _HELLOQROMARESPONSE,
  '__module__' : 'hello_qroma_pb2'
  # @@protoc_insertion_point(class_scope:HelloQromaResponse)
  })
_sym_db.RegisterMessage(HelloQromaResponse)

MathRequest = _reflection.GeneratedProtocolMessageType('MathRequest', (_message.Message,), {
  'DESCRIPTOR' : _MATHREQUEST,
  '__module__' : 'hello_qroma_pb2'
  # @@protoc_insertion_point(class_scope:MathRequest)
  })
_sym_db.RegisterMessage(MathRequest)

MathResult_Add = _reflection.GeneratedProtocolMessageType('MathResult_Add', (_message.Message,), {
  'DESCRIPTOR' : _MATHRESULT_ADD,
  '__module__' : 'hello_qroma_pb2'
  # @@protoc_insertion_point(class_scope:MathResult_Add)
  })
_sym_db.RegisterMessage(MathResult_Add)

MathResult_Subtract = _reflection.GeneratedProtocolMessageType('MathResult_Subtract', (_message.Message,), {
  'DESCRIPTOR' : _MATHRESULT_SUBTRACT,
  '__module__' : 'hello_qroma_pb2'
  # @@protoc_insertion_point(class_scope:MathResult_Subtract)
  })
_sym_db.RegisterMessage(MathResult_Subtract)

MathResult_AddAndSubtract = _reflection.GeneratedProtocolMessageType('MathResult_AddAndSubtract', (_message.Message,), {
  'DESCRIPTOR' : _MATHRESULT_ADDANDSUBTRACT,
  '__module__' : 'hello_qroma_pb2'
  # @@protoc_insertion_point(class_scope:MathResult_AddAndSubtract)
  })
_sym_db.RegisterMessage(MathResult_AddAndSubtract)

MathResponse = _reflection.GeneratedProtocolMessageType('MathResponse', (_message.Message,), {
  'DESCRIPTOR' : _MATHRESPONSE,
  '__module__' : 'hello_qroma_pb2'
  # @@protoc_insertion_point(class_scope:MathResponse)
  })
_sym_db.RegisterMessage(MathResponse)


# @@protoc_insertion_point(module_scope)
